// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import QuoteItemsController from "./quote_items_controller"
application.register("quote-items", QuoteItemsController)
